### ISSUE TITLE
App working directory is not created in Dockerfile correctly

### ISSUE THREAD

**Issue by skyline220** [rachitmehrotra1/devops-restapi#44] opened 2016-11-15 01:11 UTC
As a Developer
I need the Dockerfile to contain a command to create the /app directory
So that I can use the /app directory as the working directory

Acceptance Criteria:

When I build the docker image using the dockerfile
It should run successfully and create the /app file before making it the working directory

**Comment by carlos-guzman** [comment] 2016-11-16 03:49
As mentioned in the pull request, this is not a bug. Closing it.

https://docs.docker.com/engine/reference/builder/#workdir
"If the WORKDIR doesn’t exist, it will be created even if it’s not used in any subsequent Dockerfile instruction."

**Comment by skyline220** [comment] 2016-11-16 03:51
Carlos, this was an error on my computer hence why I fixed it. Maybe you should reply to the comment first to understand why something was logged as a BUG before you move it to the closed file. As is very clear in the class - no one is the head of a devops team, everyone is equal.

**Comment by carlos-guzman** [comment] 2016-11-16 03:54
Then add more details of your error, because it is not reproducible with the information given. What was the error given? With which command did you get the error? Did you run it on the vagrant VM?
As is very clear in the class - we are trying to make things run the same for all developers to avoid the "it works/doesn't work on my machine".

**Comment by skyline220** [comment] 2016-11-16 03:57
You keep acting as if you are the head of the team. You are not, so stop acting like it. I already spoke to Rachit about this before I even made this bug report. We both agreed it is an error. We also agreed that I would be fixing it. Now you have gone and closed items without even asking questions first. The whole purpose of this fix was to ensure  "it works/doesn't work on my machine".

**Comment by skyline220** [comment] 2016-11-16 03:58
Obviously I ran it on the Vagrant VM, how else would I get the error. I got it during the docker build command. I even verified with Rachit.

**Comment by carlos-guzman** [comment] 2016-11-16 04:03
This is not a discussion to be having here. Now you're acting as if Rachit is the head of the team. and we want more communication as a team, not blames on others.

It's just a line so it doesn't matter, let's go on and merge. You still haven't specified what your error is so that we can try to reproduce it.

**Comment by rachitmehrotra1** [comment] 2016-11-16 04:04
Yes me and Nihit spoke about it yesterday. It is supposed to automatically generate the working directory in Workdir but for some weird reason it is not creating one for him! So there is no harm in putting a mkdir as it makes sure that the directory exists! 
Also, according to the docs we technically shouldn't have a mkdir, but having one solves the issue!

**Comment by rachitmehrotra1** [comment] 2016-11-16 04:05
Also, @carlos-guzman and @skyline220  can we please have these discussions on the slack channel maybe ? 
Thanks

**Comment by skyline220** [comment] 2016-11-16 04:11
Rachit is not head of the team, no one is. Thinking everything works in accordance with a developer doc is certainly a sign of lack of experience. Regardless, you make the fix and reopen the pull request etc. since you made this mess.

**Comment by rachitmehrotra1** [comment] 2016-11-16 04:20
Merge request has been approved and merged! Closing issue.

**Closed as completed by rachitmehrotra1** 2016-11-16 04:20 UTC
Labels: bug
